### ISSUE TITLE
Cannot install latest version: Invalid checksum

### ISSUE THREAD

**Issue by almusil** [flathub/cc.arduino.IDE2#50]
Hi, 

I can't install latest version, it always reports the following error:
```
Error: While pulling app/cc.arduino.IDE2/x86_64/stable from remote flathub: Invalid checksum of length 0 expected 32
error: Failed to install cc.arduino.IDE2: While pulling app/cc.arduino.IDE2/x86_64/stable from remote flathub: Invalid checksum of length 0 expected 32
```

Tried it on two different Fedora installations (37 & 38) with the same result, any idea what might be wrong?

**Comment by rei-vilo** [comment]
Same here. Thanks!

**Comment by Krysztal112233** [comment]
Same here with Linuxmint 21.2.
To fix this, I tried switching the remote but it still doesn't work. After double checking that only this flatpak package is having problems.

**Comment by jonjahren** [comment]
Same issue with openSUSE Tumbleweed and Ubuntu 23.04

**Comment by joshuag1000** [comment]
Apologies for the late response I was away. It appears the repo might have gotten corrupt. I'll tell the system to rebuild the package and that should fix it in a few hours or so.

Again apologies for the late response.
