### ISSUE TITLE
software download failure

### ISSUE THREAD

**Issue by Strambix** [flathub/cc.arduino.IDE2#54]
attempting: flatpak install flathub cc.arduino.IDE2

results in: error: Nothing matches cc.arduino.IDE2 in remote flathub

Raspberry pi OS 64 bit

**Comment by joshuag1000** [comment]
Hi, currently an official arm build is not available for the Arduino IDE 2.x. 
This is a feature that I believe is being worked on. However, I am not an employee of Arduino so I may be incorrect and I am unable to give an ETA for when this would be available (if I am correct in thinking that this is being worked on).

If you wish to use a version of the Arduino IDE on arm hardware you will need to use the old 1.x version
(https://github.com/flathub/cc.arduino.arduinoide/)

Joshua.

**Comment by Strambix** [comment]
Joshua,
Thank you for your quick response. 
I successfully installed Arduino IDEv2 several weeks ago on my desktop. I had assumed that someone may have accidently dropped the proper link. Your thinking is much more scary!
Thank you again for taking the time to consider my post.
DavidMuskogee, OKUSANorthern HemisphereEarth.

 
 
  On Mon, Aug 28, 2023 at 7:19 AM, Joshua ***@***.***> wrote:   


Hi, currently an official arm build is not available for the Arduino IDE 2.x.
This is a feature that I believe is being worked on. However, I am not an employee of Arduino so I may be incorrect and I am unable to give an ETA for when this would be available (if I am correct in thinking that this is being worked on).

If you wish to use a version of the Arduino IDE on arm hardware you will need to use the old 1.x version
(https://github.com/flathub/cc.arduino.arduinoide/)

Joshua.
